### ISSUE TITLE
Softlock at end of the round

### ISSUE THREAD

**Issue by VanilaBOI** [LegaSource/SawTapes#1]
DISCLAIMER: This is my first time experiencing this mod.
What happend is that I got locked in a room(as host) and was forced to play a game(as the mod intended).
I didn't realize at first that the door was locked because I needed play the game, so I just screamed my head of at the door at my friends for being locked in.
I ended up dying to what I think was a mine and then when I was spectating a friend going out of the facility, they just instantly died.

After the rest of them took off with the ship and my friend(the one who died through leaving) and I got respawned, we only saw pitch black but could still talk to each other(we weren't in the ship)
ALSO there was a Information text which kept looping saying:"you've cheated, the rules were simple" or something like that.

When my friend rejoined, he was fine but since I can't just rejoin as host, I reset the server and all was fine.

What I think happend was that my friend and I counted as being part of the game, even though I was the only one to be locked in.
I could also send a video of all of this, if that helps.(It was quite funny :D)

Here are the logs. They are quite long but I can tell you that me closing the game happens at row 11050.
[SAWTRAP.txt](https://github.com/user-attachments/files/17452187/SAWTRAP.txt)

Profil Code(Uses Advanced Company):0192ab1a-0065-e50d-29d9-3bb330cf7a46

**Comment by LegaSource** [comment]
Thanks for the detailed information. Indeed, the fact that you died before starting the mini-game likely caused a variable, which initializes upon entering the room, to not reset
That makes sense, and I’ll be able to fix that

However, regarding your friend, I’m not sure what could have caused it
In which interior did this happen? The only explanation I can think of is that the game detected he entered the room as well, which is possible if the room’s collider is too large and they got close enough

I’ll add a check to ensure only one person can play the mini-game at a time

**Comment by VanilaBOI** [comment]
It was the normal facility Interior, here's a video.
The friend that died through leaving/had a black screen after respawning like me, is the one dressed in black wielding a shovel:

https://github.com/user-attachments/assets/47885d17-84a9-46db-8b29-9ef87c36bf56

**Comment by LegaSource** [comment]
I've just released an update, thanks again for the report!
Let me know if that's fix for you or if you have any other issue
